### ISSUE TITLE
Tooltip enhancement to make popup work onclick and being able to move it around the screen

### ISSUE THREAD

**Issue by alexkirp** [norcross/gravity-tooltips#14]
As a feature enhancement :+1: 
Is it possible make a tooltip popup work onclick and being able to move popup tooltip around the screen 
Many thanks

**Comment by tom112** [comment]
Would really like the onclick too in an input field

**Comment by norcross** [comment]
since I've now changed the plugin to use CSS instead of JS, this won't be feasible in it's current state.
