### ISSUE TITLE
Misplacement of the tooltip when using file upload fields

### ISSUE THREAD

**Issue by thepofo** [norcross/gravity-tooltips#15]
When using the file upload field, the span including the tooltip icon is placed inside the ginput_container, even inside the multifile upload div. See screenshot

![screen shot 2015-01-06 at 00 34 37](https://cloud.githubusercontent.com/assets/2670551/5621916/d24c499a-953b-11e4-92cb-c4831386b718.png)

This is how it is done using the other fields.
![screen shot 2015-01-06 at 00 36 42](https://cloud.githubusercontent.com/assets/2670551/5621948/2019e4a2-953c-11e4-8be7-a08800257265.png)

That way positioning the icon next to the label is impossible

**Comment by osakagreg** [comment]
Try this... Edit lib/front.php

find:  static function render_tooltip_single( $content, $tooltip ) {

and replace the line:

		return GF_Tooltips::str_replace_limit( '</div>', '</div>' . $icon, $content );

with:

                return GF_Tooltips::str_replace_limit( '</label>', '</label>' . $icon, $content );

I downloaded this today (7/13/2015) and had the same problem,  Making this modification (above) corrected it.  I haven't looked through the code enough to see if it generates problems elsewhere, but so far so good.

**Comment by norcross** [comment]
I'm actually overhauling this to use a pure CSS method, with a lot better control over filtering and layout, so keep an eye on it. otherwise you can patch your version if need be.

**Comment by norcross** [comment]
closing this for now. the new output is showing up correctly in my testing, so it may be fixed or possibly an issue with how your output is done. in addition, you can now filter the field on a per-form or per-field basis
