### ISSUE TITLE
Using entypo characters instead of img for the tooltip

### ISSUE THREAD

**Issue by jpfour23** [norcross/gravity-tooltips#16]
I'm wondering if you could help me with the code to use an entypo character in my blog theme vs. an image.  

The code that shows the correct character is: <i style="font-size:18px;" class="entypo-help-circled"></i>

I'd love to be able to inject that in instead of the default image.  Let me know what you think!  Thanks in advance!

Josh

**Comment by norcross** [comment]
I've made some substantial changes now in how this is put together, and it uses a combination of an icon font and CSS instead of an image and JS. you should be able to filter it as you see fit.
