### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by lwoods** [norcross/gravity-tooltips#17]
I installed the plugin from the zip on this site.  Then I added a tooltip to a simple one textbox Gravity form.  Nothing happens and when examining the HTML there is nothing in the HTML that would trigger the tooltip .  Is there something else I need to add to the site in order for this to work?  Also, the "visit the site" link on the plugin page is 404.  And I notice from the Norcross site that this plugin is no longer listed.

**Comment by norcross** [comment]
have you gone to the settings page and set up how you want the tooltips configured?
