### ISSUE TITLE
Trouble getting tool-tips working

### ISSUE THREAD

**Issue by CliffDugan** [norcross/gravity-tooltips#18]
I've added the tool tips to a client's site: https://www.virgobc.com/signup/, but no matter what I try I can't get the tips to display. Any insights would be appreciated.

**Comment by norcross** [comment]
can you screenshot the settings page, along with one of the fields you've entered data for?

**Comment by CliffDugan** [comment]
Thanks for your help. Cliff

![image](https://cloud.githubusercontent.com/assets/417928/7215544/cafdd7c4-e5ab-11e4-9c25-96ab6e1327ab.png)

![image](https://cloud.githubusercontent.com/assets/417928/7215548/ebb54a2e-e5ab-11e4-9af7-2a7f11978ed3.png)

**Comment by norcross** [comment]
what version of gravity forms are you currently running?

**Comment by norcross** [comment]
also, is the form a multi-page one?

**Comment by norcross** [comment]
I tested a quick thing my own with both a basic form and a multi-page, and I was able to generate the tooltips. Can you try saving the settings one then re-loading the form?

**Comment by CliffDugan** [comment]
I re-saved the settings and it worked! Thank You!

Is there any way to format the tool-tip text? I would like to add at least a simple line break in the tip if possible.

Thank you for your help!

**Comment by norcross** [comment]
in its current state I don't know for sure if it'll take a line break. try saving a `<br>` in the content and see if it sticks. the field itself may strip it out and it so a workaround would be required.

**Comment by CliffDugan** [comment]
The <br> was stripped. Could you point me to the correct php routine and file so that I might be able to override this behavior?

**Comment by norcross** [comment]
it's actually part of Gravity Forms saving function, so you'd need to do some sort of setup, like saving `{{br}}` and the converting it on the output. and even with that the JS building the tooltip may strip it out.

**Comment by CliffDugan** [comment]
Ok. Thanks for the help. I'll do some playing around with code to see what I can come up with

**Comment by Ezekielh** [comment]
Hi I'm having the same problem with gravity forms 1.9.9.  I saved the tooltip settings, reloaded the form and it still doesn't save the content added in the tooltip field.  Any help you could give me i would really appreciate it.  Thanks
