### ISSUE TITLE
Uncaught TypeError: Cannot read property 'msie' of undefined

### ISSUE THREAD

**Issue by MikevHoenselaar** [norcross/gravity-tooltips#19]
1) Downloaded the plugin and activated it
2) My settings: https://www.dropbox.com/s/prv2vm738rkzdxk/Schermafdruk%202015-04-28%2010.04.59.png?dl=0
3) Go into a form and add some text like:  
https://www.dropbox.com/s/xqes0xhsjorivpj/Schermafdruk%202015-04-28%2010.02.30.png?dl=0
4) Click on Preview and the whole form isn't showing any more.
5) removing the text displays the form again when using Preview

When I check the Console tab I see the Uncaught TypeError error message.
https://www.dropbox.com/s/7htl9yxmm0byies/Schermafdruk%202015-04-28%2010.05.37.png?dl=0

**Comment by norcross** [comment]
this error is tied to jQuery migrate not being made available. two things:

1. did you actually save the settings? (yes, it's something I need to do on activation) 
2. does the error also occur on the actual embedded form, outside of the preview?

**Comment by MikevHoenselaar** [comment]
1) yes twice
2) yes, still blank screen

**Comment by norcross** [comment]
ok. is there a URL I can look at? its tied to jQuery but I need to see the resources that are loading

**Comment by MikevHoenselaar** [comment]
http://robot-vloerverwarming.nl/robot-solution-finder/

**Comment by norcross** [comment]
the issue is you are loading an older version of jQuery (from Google CDN instead of core) which doesn't include the jQuery Migrate portion.

**Comment by MikevHoenselaar** [comment]
Changed it to 2.1.4, but error still the same.
So I took the core version.
That works.
:)

**Comment by norcross** [comment]
good deal. the core version include Migrate which handles some back compatibility stuff
