### ISSUE TITLE
qTip 1.0 has been replaced by qTip 2

### ISSUE THREAD

**Issue by kjprince** [norcross/gravity-tooltips#20]
Old library:
http://qtip1.com/demos/position/corner

New library:
http://qtip2.com/download

**Comment by norcross** [comment]
yeah, it was out when I built this. but the setup is completely different. I'm actually thinking of swapping it for jQuery UI tooltip instead.

**Comment by norcross** [comment]
decided to just ditch the JS method all together and got a straight CSS way.
