### ISSUE TITLE
Is there any way of restricting width?

### ISSUE THREAD

**Issue by U1074958** [norcross/gravity-tooltips#22]
Tool tips with long content overflow the browser window. Is there a way to force a width on the data-hint element?
![gravity_tooltips](https://cloud.githubusercontent.com/assets/14948008/12499989/d30c4178-c0fa-11e5-8a81-8e7268d5bcf3.jpg)

**Comment by norcross** [comment]
not off hand but let me see what's doable.

**Comment by norcross** [comment]
OK. I'm pushing an update that'll allow some linebreaks. You'll need to use the HTML entity `&#xa;`  and not a `<br>` for it to work.

**Comment by U1074958** [comment]
Fantastic! Thanks a lot :)
