### ISSUE TITLE
How about adding a fix width for tooltip block and break text

### ISSUE THREAD

**Issue by Key7i** [norcross/gravity-tooltips#23]
First of all thanks for this plugin.

My client have a long text which he want to display as tooltip and all this text is inline and going off the screen.
http://i.imgur.com/qp9zfiV.png

Is there way to fix this. It would be great if it work like Gravity back-end tooltip. http://i.imgur.com/C01iB7A.png

I tried to add width:500px for tooltip, while background works but text is still going of the screen. Tried word-wrap but didn't work. Any suggestion?

**Comment by norcross** [comment]
see issue #22, there isn't a way to add a defined width, however, you can add line breaks manually.
