### ISSUE TITLE
Rendering HTML tags or having a separate title field?

### ISSUE THREAD

**Issue by joleksow** [norcross/gravity-tooltips#25]
Is it possible to have a tooltip render with two types of text, e.g. a title and then the content underneath it? Or having the tooltips render HTML tags like `<h3>`?

**Comment by norcross** [comment]
The tips can't render any HTML tags. The best you could do is a line break between two lines of text, but you'd need to use the HTML entity `&#xa;` instead of a `<br>` tag.

see: https://github.com/norcross/gravity-tooltips/issues/22
