### ISSUE TITLE
Tooltip on Address field

### ISSUE THREAD

**Issue by tareqhi** [norcross/gravity-tooltips#26]
Hi, This plugin works fantastic on all of my site.
I noticed that in Address field, the tooltip icon not coming with field label, rather its going beside sub-field's label.
Plz check if it is on my side only...

**Comment by norcross** [comment]
I'm not seeing that happen on my end.

![tooltip-address-field](https://cloud.githubusercontent.com/assets/98561/14764514/58f4454e-0988-11e6-9d49-35a208127dab.png)

**Comment by tareqhi** [comment]
Can you try after the placement of sub-label? My sub fields label is set to above the field. Which means Street address, address line 2 etc. Shown before sub field.

**Comment by norcross** [comment]
so it's showing on each sublabel on the address?

**Comment by tareqhi** [comment]
![address](https://cloud.githubusercontent.com/assets/8142621/14765231/caf5c538-09fa-11e6-8e1e-449f8131af9e.png)
Sorry for translation..... the tooltip is showing on first sub-label.

**Comment by norcross** [comment]
ok, I see now. let me take a look. this may be an edge case

**Comment by norcross** [comment]
which layout type do you have set on this field?

**Comment by tareqhi** [comment]
Address type is = international
Description placement = Below inputs
Sub-Label placement = Above inputs

**Comment by norcross** [comment]
Wanna make sure we're referring to the same thing. Please confirm the settings as indicated here:

![tooltip-layout-2](https://cloud.githubusercontent.com/assets/98561/14768179/8fffc9ac-0a08-11e6-9d0d-98b93d6d1cc8.png)

**Comment by tareqhi** [comment]
Yup it's as shown in image. I just clicked on information not question mark.

**Comment by norcross** [comment]
ok. I've tested numerous configurations and they're all outputting the icon as expected. I don't know what is different about yours. is there a live URL I can see?
