### ISSUE TITLE
Hook for adding tooltip on my custom field

### ISSUE THREAD

**Issue by tareqhi** [norcross/gravity-tooltips#27]
It would be better if you add a filter/hook to permit custom field's to add tooltip option on form editor page.
I have some custom field developed for specific reason. If you add a function which can be publicly accessible will help to add tooltip option's on my fields.
Thanks

**Comment by norcross** [comment]
not totally sure what you mean by "custom fields", but there is a filter to add / remove which field types have the tooltip available to it. the filter is `gf_tooltips_allowed_fields`

**Comment by tareqhi** [comment]
Ok, got it. Thanks..
