### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Takkster** [norcross/gravity-tooltips#28]
Hey Andrew,

could you point me to installation instructions for your plugin? I couldn't find it in the WP repo and I'm not sure if it's a WP plugin or a GF plugin of some sort. I just need to know where to upload it.

Thanks!

**Comment by norcross** [comment]
this isn't kept on the WP repo, only here. you would download the zip file and upload it to your plugins folder and activate it like any other plugin.
