### ISSUE TITLE
Apply tooltip to "section"

### ISSUE THREAD

**Issue by Takkster** [norcross/gravity-tooltips#29]
Great plugin, thanks Andrew.

An additional option would be nice to place tooltips on sections. Here is an example:
![tooltips-on-section-headings](https://cloud.githubusercontent.com/assets/8360990/15241327/829b20a4-18ef-11e6-98b7-5a942b266357.jpg)

Here is the field in Gravity Forms:
![tooltips-on-section-headings2](https://cloud.githubusercontent.com/assets/8360990/15241378/e315b89a-18ef-11e6-8f24-faab9a62c658.JPG)

**Comment by norcross** [comment]
I'll see what it will take for that to work

**Comment by Takkster** [comment]
If I can help with anything, just drop me a line ;)
I'm good with CSS and HTML.

**Comment by Takkster** [comment]
Works like a charm, thanks!
