### ISSUE TITLE
Big tooltips fall off screen. How to add second line to them?

### ISSUE THREAD

**Issue by Marcoevich** [norcross/gravity-tooltips#33]
Big tooltips fall off screen. How to add second line to them? 

This would be easier if the tooltips could parse HTML. Would it be possible to add HTML support to them? So we can add linebreak attributes for example.

**Comment by norcross** [comment]
The tooltips cannot parse HTML due to how they are implemented. 

However, you can use the HTML entity for a linebreak. See https://github.com/norcross/gravity-tooltips/issues/22

**Comment by Marcoevich** [comment]
Hi @norcross ,

That's awesome! Cheers m8! :+1:

**Comment by norcross** [comment]
glad I could help!
