### ISSUE TITLE
Tooltip doesnt fold up  (Automatic Row / Line Breaks for Toolstips dont work)

### ISSUE THREAD

**Issue by emovere** [norcross/gravity-tooltips#35]
Hello, ive deactivated 1.0.1 which worked flawlessly with the latest gravity forms plugin.

After that Ive installed 2.0.3 of this plugin and activated it.

Now I have a problem. Tooltips with much text doesnt "fold up" anymore. Its just 1 long row of tooltip text. No row break. Is this normal behaviour? In the 1.0.1 release it folded up automatically just fine!
If this is normal behaviour and we have to set every line break manually this would be a downgrade.

Is this a normal behaviour? How can I fix this? (Automatic Row / Line Breaks)

**Comment by norcross** [comment]
this version is pure CSS and thus doesn't automatically break lines. please refer to the readme file on how to insert line breaks manually.

**Comment by mikeploeger** [comment]
Thank you for your fast reply!
One question, what was the reason to change this automatic line break behaviour?
Does the new version have any benefits / what are the benefits despite more work?

**Comment by norcross** [comment]
it wasn't a change in behavior, per se, but the underlying structure. the previous version used JavaScript which increased load time and could introduce accessibility issues, as the library it used was old and no longer maintained. this version uses only CSS.
