### ISSUE TITLE
ToolTip not see the end of the browser window

### ISSUE THREAD

**Issue by VadimPolh** [norcross/gravity-tooltips#39]
<img width="411" alt="2017-02-08 2 26 57" src="https://cloud.githubusercontent.com/assets/1938138/22716294/5e0cb7f2-eda6-11e6-8235-531b95f9382a.png">

**Comment by JohnClaude** [comment]
@VadimPolh  Is there any way around that issue?

**Comment by norcross** [comment]
you can add a manual line break (see the readme file for using the proper HTML entity). The CSS for making the tooltips isn't able to determine where / how to break otherwise.
