### ISSUE TITLE
Cannot access settings

### ISSUE THREAD

**Issue by geshem** [norcross/gravity-tooltips#41]
I installed the plugin and I cannot access the settings. When I click on settings from the plugin list in just reloads the page and I do not see any other menu or form item for the plugin.

**Comment by norcross** [comment]
do you have Gravity Forms installed and activated?

**Comment by geshem** [comment]
Yes of course

**Comment by norcross** [comment]
is there a "tool tips" menu item under the main Gravity Forms menu?

**Comment by geshem** [comment]
No

**Comment by norcross** [comment]
then I don't know what to tell you other than the plugin hasn't been properly activated. 

what version of Gravity Forms are you using?

**Comment by geshem** [comment]
I uploaded and activated the plugin. I'm running gravity forms Version 2.1.2

**Comment by norcross** [comment]
have you turned on `WP_DEBUG` to get any possible causes?

**Comment by geshem** [comment]
I found the issue. The plugin has a conflict with the [Members plugin](https://wordpress.org/plugins/members/).
To enable this add-on to work for custom roles, or even default WP roles that have had capabilities edited (eg via the Members plugin or similar) - the capabilities have to be explicitly (re)defined in the add-on, OR custom capabilities defined specifically for the add-on. Outside of that it only works for the Administrator role - which is also the default for Gravity Forms. Editing the capabilities or adding the gravity forms ones will allow the core Gravity Forms plugin (and even their add ons) to work for that role but not necessarily other add ons.

**Comment by norcross** [comment]
there is a filter named `gf_tooltips_admin_cap` that you can pass a new capability to. try passing your custom user role to that filter

**Comment by geshem** [comment]
I added "gf_tooltips_admin_cap" as a new capability but it did not change anything.

**Comment by norcross** [comment]
sorry for not being clear. that's the filter to pass the capability. you want to pass whatever your custom one is

**Comment by geshem** [comment]
I don't have any custom capabilities. It looks like the plugin needs to be modified to explicitly define the user capabilities so that it will work with the membership plugin.

**Comment by norcross** [comment]
can you export your Member settings so I can test locally?

**Comment by geshem** [comment]
Is it working for you with the default members plugin installed?

**Comment by norcross** [comment]
I haven't installed it yet. wanted to test against your setup.

**Comment by geshem** [comment]
I just have the standard admin setup with all permissions allowed.

**Comment by norcross** [comment]
ok. it's late here, I'll do some testing tomorrow

**Comment by geshem** [comment]
ok thank you

**Comment by norcross** [comment]
@geshem update to the most current version of the plugin (2.0.4) and let me know if this resolves the issue.

**Comment by geshem** [comment]
That update fixed the issue. Thanks!
