### ISSUE TITLE
Line break character &#10

### ISSUE THREAD

**Issue by shmuelbarkin** [norcross/gravity-tooltips#42]
Thanks for your great plugin. I just wanted to note the line break character that works for me is `&#10;` the HTML entity you mention the the README `&#xa;` is not working for me. I don't know if it's my browser or some other factor.

**Comment by shmuelbarkin** [comment]
Never mind, I was missing the semicolon `;` after adding the `;`  `&#xa;` works fine.

**Comment by norcross** [comment]
glad to hear you sorted it out!
