### ISSUE TITLE
Settings Page is not accessible.

### ISSUE THREAD

**Issue by tannerm** [norcross/gravity-tooltips#43]
The settings page requires the `gravityforms_edit_settings` capability and should allow for viewing/editing from members who have the `gform_full_access` capability.

**Comment by norcross** [comment]
isn't `gform_full_access` intended for people to access the form submissions themselves?

**Comment by norcross** [comment]
also, there is an existing `gf_tooltips_admin_cap` filter that will let you change that

**Comment by norcross** [comment]
also, I noticed the PR doesn't actually change the cap, just how it's called. what's the actual difference?

**Comment by fippy** [comment]
any news about this issue? when installing on WP 5.0.3 with Gravity 2.4.5 the tooltips settings page appears blank?

**Comment by fippy** [comment]
@tannerm fix worked for me on WP 5.0.03 on GF 2.4.5

**Comment by tannerm** [comment]
@norcross, sorry I must have missed this. If I recall correctly, I think the GF function runs through a filter that handles the appropriate capability mapping.
