### ISSUE TITLE
ToolTips Layout Type Not working

### ISSUE THREAD

**Issue by RRD100** [norcross/gravity-tooltips#45]
Good day,

**ToolTips Version 2.0.0**

2 of the options for the Layout Type does not work. 

1)  Apply tooltip to existing label
2) Insert tooltip icon next to label

Only **Insert tooltip underneath input field** works.

I am trying to display the tooltip at the end of the label.

This is part of getting our site compliance for GDPR before the 25 May 2018. Your help would be greatly appreciated.

Kind Regards,
Riaan

**Comment by norcross** [comment]
have there been changes to the field markup? the placement of the icon checks for the field and places it accordingly.

also, which type of field? some? all? screenshots would be helpful.

**Comment by RRD100** [comment]
Hi,

I was busy creating the screenshots, but it seems to be working now. Thank
you.

**Comment by norcross** [comment]
no problem at all! thanks for letting me know.
